/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as mainFeedRouteRouteImport } from './routes/(main)/feed/route'
import { Route as mainSettingsIndexRouteImport } from './routes/(main)/settings/index'
import { Route as mainProfileIndexRouteImport } from './routes/(main)/profile/index'
import { Route as mainFeedIndexRouteImport } from './routes/(main)/feed/index'
import { Route as authAuthIndexRouteImport } from './routes/(auth)/_auth.index'
import { Route as mainFeedSavedRouteImport } from './routes/(main)/feed/saved'
import { Route as mainFeedCommunityRouteImport } from './routes/(main)/feed/community'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/_auth.register'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const mainFeedRouteRoute = mainFeedRouteRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSettingsIndexRoute = mainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProfileIndexRoute = mainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFeedIndexRoute = mainFeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainFeedRouteRoute,
} as any)
const authAuthIndexRoute = authAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAuthRoute,
} as any)
const mainFeedSavedRoute = mainFeedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => mainFeedRouteRoute,
} as any)
const mainFeedCommunityRoute = mainFeedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => mainFeedRouteRoute,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/feed': typeof mainFeedRouteRouteWithChildren
  '/register': typeof authAuthRegisterRoute
  '/feed/community': typeof mainFeedCommunityRoute
  '/feed/saved': typeof mainFeedSavedRoute
  '/': typeof authAuthIndexRoute
  '/feed/': typeof mainFeedIndexRoute
  '/profile/': typeof mainProfileIndexRoute
  '/settings/': typeof mainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/register': typeof authAuthRegisterRoute
  '/feed/community': typeof mainFeedCommunityRoute
  '/feed/saved': typeof mainFeedSavedRoute
  '/': typeof authAuthIndexRoute
  '/feed': typeof mainFeedIndexRoute
  '/profile': typeof mainProfileIndexRoute
  '/settings': typeof mainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/feed': typeof mainFeedRouteRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/_auth/register': typeof authAuthRegisterRoute
  '/(main)/feed/community': typeof mainFeedCommunityRoute
  '/(main)/feed/saved': typeof mainFeedSavedRoute
  '/(auth)/_auth/': typeof authAuthIndexRoute
  '/(main)/feed/': typeof mainFeedIndexRoute
  '/(main)/profile/': typeof mainProfileIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/feed'
    | '/register'
    | '/feed/community'
    | '/feed/saved'
    | '/'
    | '/feed/'
    | '/profile/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register'
    | '/feed/community'
    | '/feed/saved'
    | '/'
    | '/feed'
    | '/profile'
    | '/settings'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/feed'
    | '/(auth)/_auth'
    | '/(auth)/_auth/register'
    | '/(main)/feed/community'
    | '/(main)/feed/saved'
    | '/(auth)/_auth/'
    | '/(main)/feed/'
    | '/(main)/profile/'
    | '/(main)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/feed': {
      id: '/(main)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof mainFeedRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof mainSettingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/profile/': {
      id: '/(main)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof mainProfileIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/feed/': {
      id: '/(main)/feed/'
      path: '/'
      fullPath: '/feed/'
      preLoaderRoute: typeof mainFeedIndexRouteImport
      parentRoute: typeof mainFeedRouteRoute
    }
    '/(auth)/_auth/': {
      id: '/(auth)/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthIndexRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(main)/feed/saved': {
      id: '/(main)/feed/saved'
      path: '/saved'
      fullPath: '/feed/saved'
      preLoaderRoute: typeof mainFeedSavedRouteImport
      parentRoute: typeof mainFeedRouteRoute
    }
    '/(main)/feed/community': {
      id: '/(main)/feed/community'
      path: '/community'
      fullPath: '/feed/community'
      preLoaderRoute: typeof mainFeedCommunityRouteImport
      parentRoute: typeof mainFeedRouteRoute
    }
    '/(auth)/_auth/register': {
      id: '/(auth)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface mainFeedRouteRouteChildren {
  mainFeedCommunityRoute: typeof mainFeedCommunityRoute
  mainFeedSavedRoute: typeof mainFeedSavedRoute
  mainFeedIndexRoute: typeof mainFeedIndexRoute
}

const mainFeedRouteRouteChildren: mainFeedRouteRouteChildren = {
  mainFeedCommunityRoute: mainFeedCommunityRoute,
  mainFeedSavedRoute: mainFeedSavedRoute,
  mainFeedIndexRoute: mainFeedIndexRoute,
}

const mainFeedRouteRouteWithChildren = mainFeedRouteRoute._addFileChildren(
  mainFeedRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainFeedRouteRoute: typeof mainFeedRouteRouteWithChildren
  mainProfileIndexRoute: typeof mainProfileIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainFeedRouteRoute: mainFeedRouteRouteWithChildren,
  mainProfileIndexRoute: mainProfileIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface authAuthRouteChildren {
  authAuthRegisterRoute: typeof authAuthRegisterRoute
  authAuthIndexRoute: typeof authAuthIndexRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthRegisterRoute: authAuthRegisterRoute,
  authAuthIndexRoute: authAuthIndexRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
